"""Update Models.

Revision ID: 1158a2218c0d
Revises: aa26e7986312
Create Date: 2024-06-18 23:35:41.145258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1158a2218c0d'
down_revision = 'aa26e7986312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    op.drop_table('inventory_items')
    op.drop_table('transactions')
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('c_id', sa.INTEGER(), server_default=sa.text("nextval('customers_c_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('c_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('c_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('c_contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('c_id', name='customers_pkey'),
    sa.UniqueConstraint('c_email', name='customers_c_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('transactions',
    sa.Column('t_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('c_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('s_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('t_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('t_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('t_category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['customers.c_id'], name='transactions_c_id_fkey'),
    sa.ForeignKeyConstraint(['s_id'], ['staff.s_id'], name='transactions_s_id_fkey'),
    sa.PrimaryKeyConstraint('t_id', name='transactions_pkey')
    )
    op.create_table('inventory_items',
    sa.Column('item_sku', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('item_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('item_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('item_sku', name='inventory_items_pkey')
    )
    op.create_table('staff',
    sa.Column('s_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('s_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('s_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('s_is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('s_contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('s_id', name='staff_pkey'),
    sa.UniqueConstraint('s_email', name='staff_s_email_key')
    )
    # ### end Alembic commands ###
