"""Removed parent_category

Revision ID: 21b66c049d75
Revises: 4f53c86c45b8
Create Date: 2024-06-19 00:12:19.597043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b66c049d75'
down_revision = '4f53c86c45b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint('inventory_items_parent_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('parent_category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_category_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('inventory_items_parent_category_id_fkey', 'inventory_items', ['parent_category_id'], ['item_sku'])

    # ### end Alembic commands ###
