"""Recreate migrations

Revision ID: 4f53c86c45b8
Revises: 
Create Date: 2024-06-18 23:54:49.591108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f53c86c45b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(), nullable=False),
    sa.Column('c_email', sa.String(), nullable=False),
    sa.Column('c_contact', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('c_id'),
    sa.UniqueConstraint('c_email')
    )
    op.create_table('inventory_items',
    sa.Column('item_sku', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.Column('item_price', sa.Float(), nullable=False),
    sa.Column('item_qty', sa.Integer(), nullable=False),
    sa.Column('parent_category_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['inventory_items.item_sku'], ),
    sa.PrimaryKeyConstraint('item_sku')
    )
    op.create_table('staff',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('s_name', sa.String(), nullable=False),
    sa.Column('s_email', sa.String(), nullable=False),
    sa.Column('s_isAdmin', sa.Boolean(), nullable=True),
    sa.Column('s_contact', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('s_id'),
    sa.UniqueConstraint('s_email')
    )
    op.create_table('transactions',
    sa.Column('t_id', sa.Integer(), nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('t_date', sa.DateTime(), nullable=False),
    sa.Column('t_amount', sa.Float(), nullable=False),
    sa.Column('t_category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['c_id'], ['customers.c_id'], ),
    sa.PrimaryKeyConstraint('t_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('staff')
    op.drop_table('inventory_items')
    op.drop_table('customers')
    # ### end Alembic commands ###
