"""removed email, added address customer

Revision ID: 99b713ceae70
Revises: bf0920917902
Create Date: 2024-07-11 20:40:14.291352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99b713ceae70'
down_revision = 'bf0920917902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('c_address', sa.String(), nullable=True))
        batch_op.drop_constraint('customers_c_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['c_contact'])
        batch_op.drop_column('c_email')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('t_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('t_items', sa.JSON(), nullable=False))
        batch_op.create_foreign_key(None, 'staff', ['s_id'], ['s_id'])
        batch_op.drop_column('t_category')
        batch_op.drop_column('t_amount')
        batch_op.drop_column('t_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('t_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('t_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('t_category', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('t_items')
        batch_op.drop_column('t_time')
        batch_op.drop_column('s_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('c_email', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('customers_c_email_key', ['c_email'])
        batch_op.drop_column('c_address')

    # ### end Alembic commands ###
