"""empty message

Revision ID: 9fc83e98b730
Revises: b0df319cac17
Create Date: 2024-07-14 23:28:48.620522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc83e98b730'
down_revision = 'b0df319cac17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_mrp', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('item_mrp')

    # ### end Alembic commands ###
