"""empty message

Revision ID: af0532fc9ccf
Revises: db1429d2eef7
Create Date: 2024-07-12 22:19:36.008469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0532fc9ccf'
down_revision = 'db1429d2eef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('item_image', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('item_image')
        batch_op.drop_column('item_category')

    # ### end Alembic commands ###
