"""Added Password Hashed field for staff

Revision ID: b2e981e52062
Revises: 21b66c049d75
Create Date: 2024-06-23 13:56:52.555107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e981e52062'
down_revision = '21b66c049d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s_passwordHash', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('s_passwordHash')

    # ### end Alembic commands ###
