"""empty message

Revision ID: db1429d2eef7
Revises: 
Create Date: 2024-07-12 22:15:12.402037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1429d2eef7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(), nullable=False),
    sa.Column('c_contact', sa.String(), nullable=True),
    sa.Column('c_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('c_id'),
    sa.UniqueConstraint('c_contact')
    )
    op.create_table('inventory_items',
    sa.Column('item_sku', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.Column('item_price', sa.Float(), nullable=False),
    sa.Column('item_qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('item_sku')
    )
    op.create_table('staff',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('s_name', sa.String(), nullable=False),
    sa.Column('s_email', sa.String(), nullable=False),
    sa.Column('s_passwordHash', sa.String(), nullable=False),
    sa.Column('s_contact', sa.String(), nullable=True),
    sa.Column('s_isAdmin', sa.Boolean(), nullable=True),
    sa.Column('s_isApproved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('s_id'),
    sa.UniqueConstraint('s_email')
    )
    op.create_table('transactions',
    sa.Column('t_id', sa.Integer(), nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('t_time', sa.DateTime(), nullable=False),
    sa.Column('t_items', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['customers.c_id'], ),
    sa.ForeignKeyConstraint(['s_id'], ['staff.s_id'], ),
    sa.PrimaryKeyConstraint('t_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('staff')
    op.drop_table('inventory_items')
    op.drop_table('customers')
    # ### end Alembic commands ###
